language: go
go:
- 1.11.x
script:
- make lint
- make test
after_script:
- make cover
env:
  secure: H29U/4imp1ceHRKLnV9YRQpsLhqa0CwLEL50wamjMDBJ07A6m7B50knRNnPbDYBa3maJ6Xbj55UgDWWnVjLpO9HW3WGb4/qnK5/8OQl6XduNRDtol0QmKw8/wC8C0iB0o1DFWv6dIdaQ5DN4fDSM5521QzVvqrQiNBQh4siD3xt4XW6aqTOz9FYWO5HTqGDcxlrNTqeMZHmoSOS3+uQ9thXW3zrN1Lz+C0AHnz+V40/DwfXm35mbJ+B3uFRfxtVZ/FyN+K4xwmhmJEco/gAd6+RQOBkNIwlmorOItND+GLYFaNIWK9y0iNeOUkmswQQP4IKKWtLwK78tTaX6jOQUkVHdzlbh6mZx2XRqKIgovct841JPFqAqNyW/UYJBxEbEMJ9/4SBEV2+/IVo9WKRSRX+WxEyQqWQCEclSUudTK3V5KdX4AeLy5X/ZYO5rHJt5Xk3WvDJW+7ozozDGXLMlJxi8G4wDgxG8lBX0OVf7xI5nnsfZFUyVpLYID6W3TUbmPOm6A4Mfdj3j4uE0/IeY2A+8rtTu1dqiEn5H1aT8CDoYoJM5vokYlcvYh9PYeAiSRVaz1SUMtWZZRfsbRaJS1qMgw+dWhXssJUNNyoeoSQR/YIlBrRIyrpZp1oeiacsXK4G2jFL7jx9zTWm6bPV0C8etBjIj3mfl7QrCX4XFOnE=
